tagsRegexps = { # search_string : ( tag, category )
                '': (u'Antojos', u'Regalos'),
                '': (u'Alquiler otro', u'Alquileres'),
                '': (u'Beca', u'Becas'),
                '': (u'Bono corp', u'Salario'),
                '': (u'Casa S Jaime', u'Alquileres'),
                'PP INVERSIONES': (u'Dividendos Bolsa', u'Inversi\xf3n'),
                '': (u'Dividendos Otro', u'Inversi\xf3n'),
                '': (u'Dividendos SFF', u'Inversi\xf3n'),
                '': (u'Negocio venta', u'Negocios'),
                '': (u'Otro Ing', u'Otros'),
                '': (u'Prestamos', u'Pr\xe9stamos'),
                'PROMOCION HSBC': (u'Promocion', u'Reembolsos'),
                '': (u'Regalo ingreso', u'Regalos'),
                '': (u'Reintegro', u'Reembolsos'),
               'INTERES PAGADO': (u'Intereses', u'Reembolsos'),
                'SUELDOS': (u'Sueldo', u'Salario'),
                '': (u'Trabajo freelance', u'Negocios'),

                'MERCADOPAGO*SKDISTRIBUTOR': (u'Antojos', u'Regalos'),
               'MERCADOPAGO*HENRY': (u'Antojos', u'Regalos'),
                'SERVICIO: TOSHL': ( u'App Finanzas', u'Servicios'),
                'SERVICIO: CTI': ( u'Celular', u'Servicios'),
                'SERVICIO: FBTL': ( u'internet', u'Servicios'),
                'PLAN ROMBO': ( u'Credito auto', u'Credito Auto'),
               'SERVICIO: PLRB': ( u'Credito auto', u'Credito Auto'),
                '': ( u'Custodio', u'Servicios'),
                '': ( u'Facultad', u'Alan'),
                '': ( u'Fernanda', u'Compras Feria'),
                'SERVICIO: GSNT': ( u'Gas', u'Servicios'),
               'GAS NATURAL': ( u'Gas', u'Servicios'),
                '': ( u'Imp Inmobiliario', u'Impuestos'), #
                'SERVICIO: PTBA': ( u'Imp Automotor', u'Impuestos'), # No estoy seguro
                'IVA CAJA AHORRO': ( u'Imp Ganancias', u'Impuestos'),
               'IMP.LEY': ( u'Imp Renta', u'Impuestos'),
                'IMP. LEY': ( u'Imp Renta', u'Impuestos'),
               'IVA UTC': ( u'Imp Renta', u'Impuestos'),
               'SELLADO UTC': ( u'Imp Renta', u'Impuestos'),
               'INTERES SALDO DEUDOR UTC': ( u'Imp Renta', u'Impuestos'),
               'VALOR AL COBRO': ( u'Imp Renta', u'Impuestos'),
               '': ( u'Autonomos', u'Impuestos'),
                '': ( u'Bienes Personales', u'Impuestos'),
               '': (u'Monotributo', u'Impuestos'),
                'LATINO SANDWICH': ( u'Latino', u'Comida Trabajo'),
               'LATINOSANDWIC': ( u'Latino', u'Comida Trabajo'),
                'REPETTO CRISTALES': ( u'Mantenimiento auto', u'Auto'),
                'ELECTROAMBAR': ( u'mantenimiento de edificios', u'Hogar y Utilidades'),
               'SANITARIOS Y FERRETERIA': ( u'mantenimiento de edificios', u'Hogar y Utilidades'),
                '': ( u'Melar', u'Compras Feria'),
                '': ( u'Multas', u'Auto'),
                'ESTABLECIMIENTO: VALLOSCURO': ( u'Nafta', u'Auto'),
               'EST SERVICIO': ( u'Nafta', u'Auto'),
                'ROLGUI SA': ( u'Nafta', u'Auto'),
               'SHELL': ( u'Nafta', u'Auto'),
               'EST YPF': ( u'Nafta', u'Auto'),
               'SERVICENTRO': ( u'Nafta', u'Auto'),
               'ESTACION DE SERVICIO': ( u'Nafta', u'Auto'),
               'COMBUSTIBLES': ( u'Nafta', u'Auto'),
                '': ( u'Navidad', u'Regalos'),
                'CONCEPTO:PCT   COMERCIO:ADMINISTRAD': ( u'Ni idea', u'Otros'),
               'ESTABLECIMIENTO: LAS CANAS': ( u'Ni idea', u'Otros'),
               'PAGOFACILGCS': ( u'Ni idea', u'Otros'),
               'GREEN LIFE': ( u'Ni idea', u'Otros'),
                '': ( u'Norma', u'Compras Feria'),
                '': ( u'Nueva Senda', u'Compras Feria'),
                "O'LIVE": ( u'Olive', u'Comida Trabajo'),
                '': ( u'Otros CF', u'Compras Feria'),
                'LUQET': ( u'Otros CT', u'Comida Trabajo'),
               'MEVERAS COMER': ( u'Otros CT', u'Comida Trabajo'),
               'MEVERASCOMER': ( u'Otros CT', u'Comida Trabajo'),
               'PALUCHINO CAFE': ( u'Otros CT', u'Comida Trabajo'),
               'DELLEPIANE': ( u'Otros CT', u'Comida Trabajo'),
               'KENTUCKY': ( u'Otros CT', u'Comida Trabajo'),
               'WOKLAVALLE': ( u'Otros CT', u'Comida Trabajo'),
               'SANTOROMERO': ( u'Otros CT', u'Comida Trabajo'),
               'MOSTAZA': ( u'Otros CT', u'Comida Trabajo'),
               'HELLSPIZZA': ( u'Otros CT', u'Comida Trabajo'),
               'JOE S BURGER': ( u'Otros CT', u'Comida Trabajo'),
               'JOESBURGERS': ( u'Otros CT', u'Comida Trabajo'),
               '180 BURGER': ( u'Otros CT', u'Comida Trabajo'),
                'DEAN & DENNYS': ( u'Otros CT', u'Comida Trabajo'),
               'GLUCK SAN TELMO': ( u'Otros CT', u'Comida Trabajo'),
               'ESTABLECIMIENTO: HVN': ( u'Otros CT', u'Comida Trabajo'),
                '': ( u'PPI', u'Dividendos'),
                '': ( u'Puerta Roja', u'Comida Trabajo'),
                'FARMACIA': ( u'Remedios', u'Salud y Cuidado Personal'),
                '': ( u'SFF', u'Dividendos'),
                '': ( u'Salidas', u'Alan'),
                'EXT. POR CAJA': ( u'Transferencia', u'Transferencia'),
                'TRANSF.CAJ.AUTOM:': ( u'Transferencia', u'Transferencia'),
                'TRANSF. ELECTRONICA': ( u'Transferencia', u'Transferencia'),
                'TRAN.ELECTRONIC': ( u'Transferencia', u'Transferencia'),
                'TRANSF. E/CTAS.': ( u'Transferencia', u'Transferencia'),
                'EXT. CAJ.AUTOM': ( u'Transferencia', u'Transferencia'),
               'EXT.CAJ.AUTOMATICO': ( u'Transferencia', u'Transferencia'),
               'DEP. EN EFVO': ( u'Transferencia', u'Transferencia'),
               'TRANSF.CAJ.AUTOM': ( u'Transferencia', u'Transferencia'),
                '': ( u'accesorios', u'Ropa y Calzado'),
                '': ( u'afluenta', u'Dividendos'),
                '': ( u'alan indefinido', u'Alan'),
                'RESTO BAR': ( u'alcohol', u'Comida y Bebidas'),
               'LA BIRRERIA': ( u'alcohol', u'Comida y Bebidas'),
                'LABIRRERIA': ( u'alcohol', u'Comida y Bebidas'),
               'MERCADOPAGO*MORFI':( u'Salir a comer', u'Comida y Bebidas'),
               'LOS RODRIGUEZ': ( u'Salir a comer', u'Comida y Bebidas'),
               'FREDO': ( u'Salir a comer', u'Comida y Bebidas'),
               'HELADERIA': ( u'Salir a comer', u'Comida y Bebidas'),
               'CASA CHINA': ( u'Salir a comer', u'Comida y Bebidas'),
               'RESTAURANT CHINO HOY': ( u'Salir a comer', u'Comida y Bebidas'),
               'HELADOS DANIEL': ( u'Salir a comer', u'Comida y Bebidas'),
               'LA ANTIGUA EUROPEA': ( u'Salir a comer', u'Comida y Bebidas'),
                'ESTABLECIMIENTO: TIHUANA': ( u'Salir a comer', u'Comida y Bebidas'),
               'BURGERKING': ( u'Salir a comer', u'Comida y Bebidas'),
               'SABOR GOURMET': ( u'Salir a comer', u'Comida y Bebidas'),
               'PEDIDOSYA.COM': ( u'Salir a comer', u'Comida y Bebidas'),
               'ABVENDING': ( u'Salir a comer', u'Comida y Bebidas'),
               'CARLITOS': ( u'Salir a comer', u'Comida y Bebidas'),
               'MCDONALDS': ( u'Salir a comer', u'Comida y Bebidas'),
               'MC DONALDS': ( u'Salir a comer', u'Comida y Bebidas'),
               'CARLOS E ENRIQUEZ': ( u'Supermercado', u'Comida y Bebidas'),
               'DIARCO': ( u'Supermercado', u'Comida y Bebidas'),
               'SUPER REAL': ( u'Supermercado', u'Comida y Bebidas'),
               'MERCADOPAGO*AUTOSERVICIO': ( u'Supermercado', u'Comida y Bebidas'),
               'ESTABLECIMIENTO: TOTAL CARNES': ( u'Supermercado', u'Comida y Bebidas'),
               'TIENDA DIA': ( u'Supermercado', u'Comida y Bebidas'),
               'ESTABLECIMIENTO: COTO': ( u'Supermercado', u'Comida y Bebidas'),
               'PANADERIA': ( u'Supermercado', u'Comida y Bebidas'),
               'ICHIBAN': ( u'Supermercado', u'Comida y Bebidas'),
               'BIG MARKET': ( u'Supermercado', u'Comida y Bebidas'),
                'AGUAPE LODGE': ( u'alojamiento', u'Ocio'),
                'TERMINAL DE OMNIBUS': ( u'avi\xf3n/micro', u'Transporte'),
               'MERCADOPAGO*SUBE': ( u'SUBE', u'Transporte'),
               'WWW.MERCADOPAGO.SUBE': ( u'SUBE', u'Transporte'),
                'PET COMPANY': ( u'comida mascotas', u'Mascotas'),
               'PETCOMPANY': ( u'comida mascotas', u'Mascotas'),
               'VETERINARIO': ( u'tratamiento mascotas', u'Mascotas'),
                '': ( u'juguetes mascota', u'Mascotas'),
                'FIDEICOMISO CROWDIUM': ( u'crowfunding', u'Dividendos'),
                'CATARATAS': ( u'diversi\xf3n', u'Ocio'),
               'PARQUE NACIONAL': ( u'diversi\xf3n', u'Ocio'),
               'IGUAZU': ( u'diversi\xf3n', u'Ocio'),
               'ESTABLECIMIENTO: CAPICUA': ( u'diversi\xf3n', u'Ocio'),
               'TESORERIA GENERAL': ( u'diversi\xf3n', u'Ocio'),
               'ESTABLECIMIENTO: EJE': ( u'diversi\xf3n', u'Ocio'),
               'ESTABLECIMIENTO: LA ROTONDA': ( u'diversi\xf3n', u'Ocio'),
               'MERCADOPAGO*LAGRINGA': ( u'diversi\xf3n', u'Ocio'),
               'SHOWCASE': ( u'Cine', u'Ocio'),
                'SERVICIO: MSI': ( u'impuesto Municipal', u'Impuestos'),
               'MUNICIP SAN ISIDRO': ( u'impuesto Municipal', u'Impuestos'),
                '': ( u'indefinido esther', u'Esther'),
                'SERVICIO: ENOR': ( u'luz', u'Servicios'),
                'CLICKYRESERVA': ( u'Otro serv', u'Servicios'),
                'SERVICIO: NRJA': ( u'Tarjeta', u'Servicios'),
               'TARJNARANJA2': ( u'Tarjeta', u'Servicios'),
                'DEB.AUTOMATICO VISA': ( u'Tarjeta', u'Servicios'),
                'DEB.AUTOMATICO ARGENCARD': ( u'Tarjeta', u'Servicios'),
                'SERVICIO: VIRI': ( u'Tarjeta', u'Servicios'),
               'VIPE IDENTIFICACION': ( u'Tarjeta', u'Servicios'),
                'Netflix.com': ( u'Netflix', u'Servicios'),
               'NetflixINC': ( u'Netflix', u'Servicios'),
                '': ( u'Omint', u'Servicios'),
                '': ( u'Work N Travel', u'Servicios'),
                'MERCADOPAGO*JAVIERMARCON': ( u'mercadolibre', u'Dividendos'),
               'MERCADOPAGO*MERCADOPAGO': ( u'mercadolibre', u'Dividendos'),
                '': ( u'schwab', u'Dividendos'),
                '': ( u'seguro auto', u'Auto')}